version: "3.7"

services:
  restaurante: 
    build: restaurante-rest-base
    ports:
      - 8080:8080

  opiniones:
    build: opiniones-rest-base
    ports:
       - 5110:5110

  mongo:
    build: mongo
    
